@base_url = http://localhost:8080
@deploy_url = http://35.77.104.40:8080
@use_url = {{deploy_url}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDI2OTg4MjksImlhdCI6MTc0MjYxMjQyOX0.HRD249I2gAJQcD3Mle9kEMS1AHDqC3Z8Vk75d1CTWvA

### GET Request
GET {{use_url}}/api/v1/works

### GET Request with query parameter
GET {{use_url}}/api/v1/works?name=John

### POST Request
POST {{use_url}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "John Brown",
  "email": "john.brown@example.com",
  "password": "password",
  "nickname": "nyaaaaa"
}

### POST Request
POST {{use_url}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "john.brown@example.com",
  "password": "password"
}

### GET Request
GET {{use_url}}/api/v1/auth/me
Authorization: Bearer {{token}}



