version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: processing-api-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=processing_user
      - DB_PASSWORD=processing_password
      - DB_NAME=processing_platform
      - JWT_SECRET=your-jwt-secret-key-change-this
      - TOKEN_EXPIRY=24
      - UPLOAD_DIR=/app/uploads
      - MAX_UPLOAD_SIZE=50
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - processing_network

  db:
    image: mariadb:10.6
    container_name: processing-db-dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=processing_platform
      - MYSQL_USER=processing_user
      - MYSQL_PASSWORD=processing_password
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - processing_network

  # PHPMyAdminを追加（オプション）
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=processing_user
      - PMA_PASSWORD=processing_password
    depends_on:
      - db
    networks:
      - processing_network

networks:
  processing_network:
    driver: bridge

volumes:
  db_data_dev: