version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: processing-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-processing_user}
      - DB_PASSWORD=${DB_PASSWORD:-processing_password}
      - DB_NAME=${DB_NAME:-processing_platform}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-change-this}
      - TOKEN_EXPIRY=24
      - UPLOAD_DIR=/app/uploads
      - MAX_UPLOAD_SIZE=50
      - GIN_MODE=release
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - processing_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  db:
    image: mariadb:10.6
    container_name: processing-db
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${DB_NAME:-processing_platform}
      - MYSQL_USER=${DB_USER:-processing_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-processing_password}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - processing_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  processing_network:
    driver: bridge

volumes:
  db_data:
    name: processing_db_data
