FROM golang:1.18-alpine

# 依存関係のためのパッケージをインストール
RUN apk add --no-cache gcc musl-dev

# 作業ディレクトリを設定
WORKDIR /app

# Go Modulesのキャッシュレイヤーを作成
COPY go.mod go.sum ./
RUN go mod download

# ソースコードをコピー
COPY . .

# マイグレーションコマンドを実行
ENTRYPOINT ["go", "run", "cmd/migrate/main.go"]